version: "3.8"

services:
  frontend:
    build: .
    container_name: imhere-frontend
    restart: unless-stopped
    networks:
      - imhere-network
    ports:
      - "3000:80"
    #expose:
    #  - "80"

networks:
  imhere-network:
    external: true
